### ISSUE TITLE
Other player opening the menu/inventory in splitscreen causing weird behavior

### ISSUE THREAD

**Issue by ChainsLunatic** [alanperrow/StardewModding#25]
If player b opens the menu or inventory the quick stack button will disappear for player a or jump to another random position on its screen. Seems to be fixed in unpublished 1.5.

**Comment by alanperrow** [comment]
Convenient Inventory 1.5 has been released on Nexus Mods. Closing this as issue has been fixed in this version and is now available. Thank you!
